#ifndef OFFSETS_H
#define OFFSETS_H

#define size_of_attribute(Struct, Attribute) sizeof(((Struct *)0)->Attribute)

#include "typedef.h"

#define HEADER_NODE_TYPE_SIZE sizeof(uint8_t)
#define HEADER_IS_ROOT_SIZE sizeof(uint8_t)
#define HEADER_PARENT_POINTER_SIZE sizeof(uint32_t)
#define HEADER_NUM_CELLS_SIZE sizeof(uint32_t)
#define HEADER_RIGHT_NUM_SIZE sizeof(uint32_t)
#define HEADER_NEXT_LEAF sizeof(uint32_t)

// Row size of known columns
#define ID_SIZE size_of_attribute(Row, id)
#define USERNAME_SIZE COLUMN_USERNAME_SIZE
#define EMAIL_SIZE COLUMN_EMAIL_SIZE

// Header of a node size
#define NODE_TYPE_SIZE HEADER_NODE_TYPE_SIZE
#define IS_ROOT_SIZE HEADER_IS_ROOT_SIZE
#define PARENT_POINTER_SIZE HEADER_PARENT_POINTER_SIZE
#define NUM_CELLS_SIZE HEADER_NUM_CELLS_SIZE
#define NEXT_LEAF_SIZE HEADER_NEXT_LEAF
#define HEADER_SIZE (NODE_TYPE_SIZE + IS_ROOT_SIZE + PARENT_POINTER_SIZE + NUM_CELLS_SIZE + NEXT_LEAF_SIZE)

// Row offsets
#define ID_OFFSET 0
#define USERNAME_OFFSET (ID_OFFSET + ID_SIZE)
#define EMAIL_OFFSET (USERNAME_OFFSET + USERNAME_SIZE)
#define ROW_SIZE (ID_SIZE + USERNAME_SIZE + EMAIL_SIZE)
#define LEAF_NODE_CELL_SIZE (ID_SIZE + ROW_SIZE)

// Node offsets
#define NODE_TYPE_OFFSET 0
#define IS_ROOT_OFFSET (NODE_TYPE_OFFSET + NODE_TYPE_SIZE)
#define PARENT_POINTER_OFFSET (IS_ROOT_OFFSET + IS_ROOT_SIZE)
#define NUM_CELLS_OFFSET (PARENT_POINTER_OFFSET + PARENT_POINTER_SIZE)
#define NEXT_LEAF_OFFSET (NUM_CELLS_OFFSET + NUM_CELLS_SIZE)
#define INITIAL_CELL_OFFSET (NEXT_LEAF_OFFSET + NEXT_LEAF_SIZE)

// Internal node offsets
#define INTERNAL_NODE_RIGHT_NUM HEADER_SIZE
#define INTERNAL_NODE_HEADER_SIZE (INTERNAL_NODE_RIGHT_NUM + HEADER_RIGHT_NUM_SIZE)

#define INTERNAL_CELL_SIZE sizeof(uint32_t)
#define INTERNAL_KEY_SIZE sizeof(uint32_t)
#define INTERNAL_NODE_CELL_SIZE (INTERNAL_CELL_SIZE + INTERNAL_KEY_SIZE)

// Useful constants to know about
#define ROWS_PER_PAGE (PAGE_SIZE / ROW_SIZE)
#define AVAILABLE_CELLS_SPACE (PAGE_SIZE - HEADER_SIZE)
#define CELLS_PER_PAGE (AVAILABLE_CELLS_SPACE / LEAF_NODE_CELL_SIZE)
#define TABLE_MAX_SIZE (TABLE_MAX_PAGES * ROWS_PER_PAGE)
#define KEY_VALUE_PER_PAGE (AVAILABLE_CELLS_SPACE / INTERNAL_NODE_CELL_SIZE)

#endif