// Row size of known columns
const uint32_t ID_SIZE = size_of_attribute(Row, id);
const uint32_t USERNAME_SIZE = COLUMN_USERNAME_SIZE;
const uint32_t EMAIL_SIZE = COLUMN_EMAIL_SIZE;

// Header of a node size
const uint8_t NODE_TYPE_SIZE = HEADER_NODE_TYPE_SIZE;
const uint8_t IS_ROOT_SIZE = HEADER_IS_ROOT_SIZE;
const uint32_t PARENT_POINTER_SIZE = HEADER_PARENT_POINTER_SIZE;
const uint32_t NUM_CELLS_SIZE = HEADER_NUM_CELLS_SIZE;
const uint32_t NEXT_LEAF_SIZE = HEADER_NEXT_LEAF;
const uint32_t HEADER_SIZE = NODE_TYPE_SIZE + IS_ROOT_SIZE + PARENT_POINTER_SIZE + NUM_CELLS_SIZE + NEXT_LEAF_SIZE;

// Row offsets
const uint32_t ID_OFFSET = 0;
const uint32_t USERNAME_OFFSET = ID_OFFSET + ID_SIZE;
const uint32_t EMAIL_OFFSET = USERNAME_OFFSET + USERNAME_SIZE;
const uint32_t ROW_SIZE = ID_SIZE + USERNAME_SIZE + EMAIL_SIZE;
const uint32_t LEAF_NODE_CELL_SIZE = ID_SIZE + ROW_SIZE;

// Node offsets
const uint32_t NODE_TYPE_OFFSET = 0;
const uint32_t IS_ROOT_OFFSET = NODE_TYPE_OFFSET + NODE_TYPE_SIZE;
const uint32_t PARENT_POINTER_OFFSET = IS_ROOT_OFFSET + IS_ROOT_SIZE;
const uint32_t NUM_CELLS_OFFSET = PARENT_POINTER_OFFSET + PARENT_POINTER_SIZE;
const uint32_t NEXT_LEAF_OFFSET = NUM_CELLS_OFFSET + NEXT_LEAF_SIZE;
const uint32_t INITIAL_CELL_OFFSET = NEXT_LEAF_OFFSET + NUM_CELLS_SIZE;

// Internal node offsets
const uint32_t INTERNAL_NODE_RIGHT_NUM = HEADER_SIZE;
const uint32_t INTERNAL_NODE_HEADER_SIZE = INTERNAL_NODE_RIGHT_NUM + HEADER_RIGHT_NUM_SIZE;

const uint32_t INTERNAL_CELL_SIZE = sizeof(uint32_t);
const uint32_t INTERNAL_KEY_SIZE = sizeof(uint32_t);
const uint32_t INTERNAL_NODE_CELL_SIZE = INTERNAL_CELL_SIZE + INTERNAL_KEY_SIZE;

// Useful constants to know about
const uint32_t ROWS_PER_PAGE = PAGE_SIZE / ROW_SIZE;
const uint32_t AVAILABLE_CELLS_SPACE = PAGE_SIZE - HEADER_SIZE;
const uint32_t CELLS_PER_PAGE = AVAILABLE_CELLS_SPACE / LEAF_NODE_CELL_SIZE;
const uint32_t TABLE_MAX_SIZE = TABLE_MAX_PAGES * ROWS_PER_PAGE;
const uint32_t KEY_VALUE_PER_PAGE = AVAILABLE_CELLS_SPACE / INTERNAL_NODE_CELL_SIZE;
